const ROUTES_NAVIGATION = {
  HOME: "/",
  PRODUCT_LIST: "/product-list",
  LOGIN: "/login",
  PRODUCT_DETAILS: "/product",
  PROFILE: "/profile",
  USER_ACCOUNT: "useraccount",
  USER_ORDER: "order",
  USER_WISHLIST: "/profile/wishlist",
  USER_ADDRESS: "address",
  USER_PAYMENT: "payment",
  USER_SETTING: "setting",
  CART: "/cart",
  COUPON_APPLY: "/coupon-apply",
  OFFERSCOUPON: "/offers-coupon",
  ALL_COUPONS_LIST: "/allcoupons",
  MOB_CATEGORY: "/mob-all-category",
  COLLECTION: "/collection",
  BROWSE: "/browse",
  SEARCH: "/search",
  MOBILE_SEARCH: "/mobsearch",
  CHANGE_LOCATION: "/change-location",
  PROCEED_PAYMENT: "/proceed-payment",
  ORDER_CONFIRM: "/order-confirm",
  MY_WALLET: "wallet",
  WISH_LIST: "wishlist",
  RATING_REVIEW: "/rating-review",
  ABOUT_US: "/about-us",
  CUSTOMER_SUPPORT: "/customer-support",
  ORDER_CHECKLIST: "/order-checklist",
  ORDER_DELAY: "/order-delay",
  ORDER_RETURN: "/order-return-request",
  ORDER_CANLE_SUMMARY: "/order-cancle-summary",
  ORDER_DETAIL_SUMMARY: "/order-detail-summary",
  ORDER_CANCLE: "/order-cancle",
  ORDER_TIMER: "/order-timer",
  ORDER_LIVE_TRACK: "/order-track",
  CUSTOMER_SUPPORT_FAQ: "/customer-support-faq",
  REQUEST_NEW_PRODUCT: "/request-new-product",
  REQUEST_NEW_PRODUCT_SEARCH: "/request-new-product-search",
  OTP_VERIFICATION: "/otp-verification",
  ACCOUNT_REGISTER: "/account-register",
  CREDITO_COIN: "/credito-coin",
  EDOBO_STORE: "/edobo-store",

};

export default ROUTES_NAVIGATION;
